"""Command line interface.

Every command prints its fully resolved configuration before doing any work, so a terminal
log is a complete record of what was run -- including the values that were defaulted rather
than passed. That convention is lifted from ``qecgen.cli`` and is worth keeping: a report
that cannot be tied back to the settings that produced it is a report nobody can reproduce.
"""

from __future__ import annotations

import json
from collections.abc import Mapping
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console
from rich.table import Table

from nexus_genomics.adapters import ADAPTERS, get_adapter
from nexus_genomics.adapters.base import GatedSourceUnavailableError
from nexus_genomics.common import PACKAGE_VERSION, hash_text
from nexus_genomics.compliance import audit_email_compliance
from nexus_genomics.compliance import render_markdown as render_compliance
from nexus_genomics.encoding import EncodingMode, LengthPolicy
from nexus_genomics.nexus_csv import EXTENSION
from nexus_genomics.pipeline import ConvertOptions, convert
from nexus_genomics.projection import projected_path, single_target_projections
from nexus_genomics.run_receipt import (
    build_conversion_run_receipt,
    write_conversion_run_receipt,
)
from nexus_genomics.validation import compare_runs, render_markdown, validate_file

app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help=(
        "Convert public genomic datasets into a Nexus-shaped CSV "
        "(compatibility unverified), without inventing labels."
    ),
)
console = Console()

DEFAULT_CONFIG = Path("config/default.yaml")
DEFAULT_RAW = Path("data/raw")
DEFAULT_OUT = Path("outputs")
DEFAULT_REPORTS = Path("reports")
DEFAULT_STRICT_OUT = DEFAULT_OUT / "strict"


class Profile(StrEnum):
    DEMO = "demo"
    FULL = "full"


def _load_config(path: Path) -> tuple[dict[str, Any], str]:
    text = path.read_text(encoding="utf-8")
    parsed: dict[str, Any] = yaml.safe_load(text)
    return parsed, hash_text(text)


def _options(config: dict[str, Any]) -> ConvertOptions:
    window = config["window"]
    return ConvertOptions(
        width=int(window["length"]),
        policy=LengthPolicy(window["policy"]),
        stride=int(window["stride"]),
        mode=EncodingMode(config["encoding"]["mode"]),
        max_windows_per_sample=window.get("max_windows_per_sample"),
    )


def _target_layout(config: dict[str, Any], strict_single_target: bool | None) -> str:
    configured = str(config["output"]["target_layout"])
    if configured not in {"native", "single"}:
        raise ValueError(f"output.target_layout must be 'native' or 'single', got {configured!r}")
    if strict_single_target is None:
        return configured
    return "single" if strict_single_target else "native"


def _profile_options(config: dict[str, Any], source: str, profile: Profile) -> dict[str, Any]:
    source_config = config.get("sources", {}).get(source)
    if not isinstance(source_config, Mapping):
        raise ValueError(f"configuration has no sources.{source} block")
    if profile.value not in source_config:
        raise ValueError(f"sources.{source} has no {profile.value!r} profile block")
    options = source_config[profile.value]
    if not isinstance(options, Mapping):
        raise TypeError(
            f"sources.{source}.{profile.value} must be a mapping, got {type(options).__name__}"
        )
    return dict(options)


def _echo_config(**values: Any) -> None:
    table = Table(show_header=False, box=None, pad_edge=False)
    for key, value in values.items():
        table.add_row(f"[dim]{key}[/dim]", str(value))
    console.print(table)
    console.print()


@app.command()
def audit(
    raw_dir: Annotated[Path, typer.Option(help="Where raw downloads live.")] = DEFAULT_RAW,
    out: Annotated[Path, typer.Option(help="Write the audit here.")] = DEFAULT_REPORTS
    / "source_audit_status.md",
) -> None:
    """Report what each source actually is, and whether it can be converted right now."""
    _echo_config(command="audit", raw_dir=raw_dir, out=out, version=PACKAGE_VERSION)

    table = Table(title="Source availability")
    for column in ("source", "target", "ready", "detail"):
        table.add_column(column, overflow="fold")

    lines = ["# Source availability", "", f"Generated by nexus-genomics {PACKAGE_VERSION}.", ""]
    for name, adapter in ADAPTERS.items():
        status = adapter.availability(raw_dir / name)
        table.add_row(
            name,
            adapter.target_description.split(".")[0],
            "[green]yes[/green]" if status.ready else "[red]no[/red]",
            status.detail,
        )
        lines += [
            f"## `{name}`",
            "",
            f"- **Source**: {adapter.source_url}",
            f"- **Target**: {adapter.target_description}",
            f"- **Licence**: {adapter.licence}",
            f"- **Ready**: {'yes' if status.ready else 'NO'} — {status.detail}",
        ]
        if status.expected_files:
            lines.append(f"- **Expected files**: `{'`, `'.join(status.expected_files)}`")
        if status.manual_steps:
            lines += ["", "```text", status.manual_steps, "```"]
        lines.append("")
    console.print(table)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    console.print(f"[green]wrote[/green] {out}")


@app.command()
def compliance(
    profile: Annotated[Profile, typer.Option(help="Output profile to audit.")] = Profile.DEMO,
    config: Annotated[Path, typer.Option(help="Configuration file.")] = DEFAULT_CONFIG,
    raw_dir: Annotated[Path, typer.Option(help="Where raw downloads live.")] = DEFAULT_RAW,
    out_dir: Annotated[Path, typer.Option(help="Where strict outputs live.")] = DEFAULT_STRICT_OUT,
    reports_dir: Annotated[Path, typer.Option(help="Where to write reports.")] = DEFAULT_REPORTS,
) -> None:
    """Audit strict outputs against the email contract without inventing evidence."""
    cfg, digest = _load_config(config)
    enabled = [name for name in ADAPTERS if cfg["sources"].get(name, {}).get("enabled", False)]
    for name in enabled:
        _profile_options(cfg, name, profile)
    _echo_config(
        command="compliance",
        profile=profile.value,
        config=f"{config} (blake2b {digest[:16]}...)",
        raw_dir=raw_dir,
        out_dir=out_dir,
        reports_dir=reports_dir,
        version=PACKAGE_VERSION,
    )
    report = audit_email_compliance(
        ADAPTERS,
        raw_dir,
        out_dir,
        profile.value,
        config_digest=digest,
        enabled_source_keys=enabled,
    )

    reports_dir.mkdir(parents=True, exist_ok=True)
    json_path = reports_dir / "email_compliance_report.json"
    markdown_path = reports_dir / "email_compliance_report.md"
    json_path.write_text(report.to_json(), encoding="utf-8")
    markdown_path.write_text(render_compliance(report), encoding="utf-8")

    table = Table(title="Email compliance")
    for column in ("requirement", "status", "detail"):
        table.add_column(column, overflow="fold")
    colors = {
        "PASS": "green",
        "BLOCKED_EXTERNAL": "yellow",
        "UNSUPPORTED_BY_SOURCE": "yellow",
        "FAIL": "red",
    }
    for check in report.checks:
        status = check.status.value
        table.add_row(
            check.requirement, f"[{colors[status]}]{status}[/{colors[status]}]", check.detail
        )
    console.print(table)
    console.print(f"[green]wrote[/green] {json_path}")
    console.print(f"[green]wrote[/green] {markdown_path}")
    if not report.exit_ok:
        raise typer.Exit(code=1)


@app.command(name="convert")
def convert_source(
    source: Annotated[str, typer.Argument(help=f"One of: {', '.join(ADAPTERS)}")],
    config: Annotated[Path, typer.Option(help="Configuration file.")] = DEFAULT_CONFIG,
    profile: Annotated[Profile, typer.Option(help="'demo' or 'full'.")] = Profile.DEMO,
    raw_dir: Annotated[Path, typer.Option(help="Where raw downloads live.")] = DEFAULT_RAW,
    out_dir: Annotated[Path, typer.Option(help="Where to write outputs.")] = DEFAULT_OUT,
    strict_single_target: Annotated[
        bool | None,
        typer.Option(
            "--strict-single-target/--native-targets",
            help="Write one table per target or preserve the source's native target block.",
        ),
    ] = None,
) -> list[Path]:
    """Convert one source into a Nexus CSV plus its sidecars."""
    cfg, digest = _load_config(config)
    target_layout = _target_layout(cfg, strict_single_target)
    adapter = get_adapter(source)
    options = _profile_options(cfg, source, profile)
    convert_options = _options(cfg)

    _echo_config(
        command="convert",
        source=source,
        profile=profile.value,
        config=f"{config} (blake2b {digest[:16]}...)",
        window=f"{convert_options.width} x {convert_options.policy.value}",
        encoding=convert_options.mode.value,
        target_layout=target_layout,
        source_options=options,
        out_dir=out_dir,
    )

    out_path = out_dir / f"{adapter.name}_{profile.value}{EXTENSION}"
    with console.status(f"loading {source}..."):
        loaded = adapter.load(raw_dir / source, options)
    console.print(f"loaded [bold]{len(loaded.records)}[/bold] records")

    conversions = [(loaded, out_path, adapter.target_description)]
    if target_layout == "single":
        conversions = [
            (
                projection.source,
                projected_path(out_path, projection.slug),
                (
                    f"{adapter.target_description} Selected target: {projection.name}."
                    if projection.name
                    else adapter.target_description
                ),
            )
            for projection in single_target_projections(loaded)
        ]

    table_paths: list[Path] = []
    for conversion_source, conversion_path, target_description in conversions:
        extra_manifest = dict(conversion_source.manifest_extra)
        extra_manifest["target_layout"] = target_layout
        outcome = convert(
            conversion_source,
            conversion_path,
            convert_options,
            source_name=adapter.name,
            source_url=adapter.source_url,
            licence=adapter.licence,
            target_description=target_description,
            notes=(
                "Integers are categorical tokens (A=1..Z=26, 0=padding); their numerical "
                "distance has no biological meaning. Nexus compatibility is NOT verified."
            ),
            config_digest=digest,
            extra_manifest=extra_manifest,
        )
        table_paths.append(outcome.path)
        console.print(
            f"[green]wrote[/green] {outcome.n_rows} rows x "
            f"{outcome.n_features + 1 + conversion_source.n_targets} columns"
        )
        for path in outcome.written:
            console.print(f"  {path}")
        if outcome.quarantine:
            console.print(f"[yellow]quarantined[/yellow] {len(outcome.quarantine)} record(s)")
        if outcome.truncated_residues:
            console.print(f"[yellow]truncated[/yellow] {outcome.truncated_residues:,} residues")
    return table_paths


@app.command()
def convert_all(
    config: Annotated[Path, typer.Option(help="Configuration file.")] = DEFAULT_CONFIG,
    profile: Annotated[Profile, typer.Option(help="'demo' or 'full'.")] = Profile.DEMO,
    raw_dir: Annotated[Path, typer.Option(help="Where raw downloads live.")] = DEFAULT_RAW,
    out_dir: Annotated[Path, typer.Option(help="Where to write outputs.")] = DEFAULT_OUT,
    strict_single_target: Annotated[
        bool | None,
        typer.Option(
            "--strict-single-target/--native-targets",
            help="Write one table per target or preserve each source's native target block.",
        ),
    ] = None,
) -> None:
    """Convert every enabled source, reporting rather than aborting on the gated ones."""
    cfg, digest = _load_config(config)
    target_layout = _target_layout(cfg, strict_single_target)
    _echo_config(
        command="convert-all",
        profile=profile.value,
        config=config,
        target_layout=target_layout,
        out_dir=out_dir,
    )
    enabled = [name for name in ADAPTERS if cfg["sources"].get(name, {}).get("enabled", False)]
    initial_receipt = build_conversion_run_receipt(
        out_dir,
        complete=False,
        profile=profile.value,
        target_layout=target_layout,
        config_hash=digest,
        enabled_source_keys=enabled,
        successfully_converted_source_keys=(),
        externally_gated_source_keys=(),
        table_paths=(),
    )
    write_conversion_run_receipt(out_dir, initial_receipt)
    for name in enabled:
        _profile_options(cfg, name, profile)

    failures: list[tuple[str, str]] = []
    gated: list[tuple[str, str]] = []
    converted: list[str] = []
    generated_paths: list[Path] = []
    for name in ADAPTERS:
        if not cfg["sources"].get(name, {}).get("enabled", False):
            console.print(f"[dim]skipping {name} (disabled in config)[/dim]")
            continue
        console.rule(name)
        try:
            paths = convert_source(
                name,
                config,
                profile,
                raw_dir,
                out_dir,
                target_layout == "single",
            )
            converted.append(name)
            generated_paths.extend(paths)
        except GatedSourceUnavailableError as exc:
            # A gated source with no file present is an expected state, not a failure: the
            # whole point of convert-all is that it finishes and reports.
            gated.append((name, str(exc).splitlines()[0]))
            console.print(f"[yellow]{name} is not available[/yellow] (gated download)")
        except Exception as exc:
            failures.append((name, f"{type(exc).__name__}: {exc}"))
            console.print(f"[red]{name} could not be converted[/red]: {type(exc).__name__}")
            console.print(f"[dim]{exc}[/dim]")
    console.rule("summary")
    for name, detail in gated:
        console.print(f"[yellow]{name}[/yellow]: awaiting a manual download — {detail}")
    for name, detail in failures:
        console.print(f"[red]{name}[/red]: {detail.splitlines()[0]}")
    final_receipt = build_conversion_run_receipt(
        out_dir,
        complete=not failures,
        profile=profile.value,
        target_layout=target_layout,
        config_hash=digest,
        enabled_source_keys=enabled,
        successfully_converted_source_keys=converted,
        externally_gated_source_keys=[name for name, _detail in gated],
        table_paths=generated_paths,
    )
    write_conversion_run_receipt(out_dir, final_receipt)
    if not failures and not gated:
        console.print("[green]every enabled source converted[/green]")
    if failures:
        # A missing gated file exits 0; anything else must not. Otherwise a scheduled run
        # that ran out of memory looks identical to one waiting on a download, and the next
        # step consumes the previous run's stale outputs believing they are fresh.
        raise typer.Exit(code=1)


@app.command()
def validate(
    paths: Annotated[list[Path], typer.Argument(help="Nexus CSVs to validate.")],
    config: Annotated[Path, typer.Option(help="Configuration file.")] = DEFAULT_CONFIG,
    reports_dir: Annotated[Path, typer.Option(help="Where to write reports.")] = DEFAULT_REPORTS,
    write_reports: Annotated[bool, typer.Option(help="Write md + json reports.")] = True,
) -> None:
    """Run every check against one or more written tables."""
    cfg, digest = _load_config(config)
    vcfg = cfg.get("validation", {})
    _echo_config(command="validate", files=len(paths), config=config, reports_dir=reports_dir)

    results = [
        validate_file(
            path,
            sample_size=int(vcfg.get("round_trip_sample_size", 25)),
            seed=int(vcfg.get("round_trip_seed", 0)),
        )
        for path in paths
    ]

    table = Table(title="Validation")
    for column in ("file", "checks", "failed", "rows", "cols", "result"):
        table.add_column(column, overflow="fold")
    for result in results:
        failed = sum(1 for c in result.checks if not c.passed)
        table.add_row(
            Path(result.path).name,
            str(len(result.checks)),
            str(failed),
            str(result.stats.get("row_count", "-")),
            str(result.stats.get("column_count", "-")),
            "[green]PASS[/green]" if result.ok else "[red]FAIL[/red]",
        )
    console.print(table)
    for result in results:
        for check in result.checks:
            if not check.passed:
                console.print(f"[red]{Path(result.path).name} :: {check.name}[/red]")
                console.print(f"  {check.detail}")

    if write_reports:
        reports_dir.mkdir(parents=True, exist_ok=True)
        payload = {
            "generator": f"nexus-genomics {PACKAGE_VERSION}",
            "config_hash": digest,
            "files": [r.to_json_dict() for r in results],
            "all_pass": all(r.ok for r in results),
        }
        (reports_dir / "validation_report.json").write_text(
            json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        (reports_dir / "validation_report.md").write_text(
            render_markdown(results, {"config_hash": digest}), encoding="utf-8"
        )
        console.print(f"[green]wrote[/green] {reports_dir / 'validation_report.json'}")
        console.print(f"[green]wrote[/green] {reports_dir / 'validation_report.md'}")

    if not all(r.ok for r in results):
        raise typer.Exit(code=1)


@app.command()
def reproduce(
    first: Annotated[Path, typer.Argument(help="A table from one run.")],
    second: Annotated[Path, typer.Argument(help="The same table from a second run.")],
) -> None:
    """Confirm two runs of the same configuration produced byte-identical tables."""
    _echo_config(command="reproduce", first=first, second=second)
    check = compare_runs(first, second)
    console.print(f"{'[green]PASS[/green]' if check.passed else '[red]FAIL[/red]'} {check.detail}")
    if not check.passed:
        raise typer.Exit(code=1)


@app.command()
def formats() -> None:
    """Describe the output format, including what is NOT claimed about it."""
    console.print(
        "[bold]nexus-genomics-csv v1[/bold]\n\n"
        "  <name>.ml.csv            one header row, no '#'; sample_id, target(s), position_*\n"
        "  <name>.ml.manifest.json   format/version/columns/manifest; the file's magic line\n"
        "  <name>.ml.samples.csv     per-sample provenance, kept out of the model table\n\n"
        "Encoding: A=1 .. Z=26, 0 reserved for padding. These are CATEGORICAL TOKENS;\n"
        "their numerical distance has no biological meaning.\n\n"
        "[yellow]Nexus compatibility is not claimed.[/yellow] This format matches the CSV shape\n"
        "described in the brief and mirrors the conventions of qecgen's ml_csv exporter.\n"
        "No fixture supplied by the Nexus team has been run against it.\n\n"
        "This is [bold]not[/bold] a qecgen-ml-csv file: that format's reader accepts only the\n"
        "literal cells '0' and '1', and would refuse an A=1..Z=26 table."
    )


if __name__ == "__main__":
    app()
